# ios/Podfile

require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '14.0'
install! 'cocoapods', :deterministic_uuids => false

# DISABLE NEW ARCH
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

# REQUIRED FOR RN 0.73+
prepare_react_native_project!

target 'FocusTube' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :fabric_enabled => false
    # Flipper removed — not needed
  )

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end